name: Deploy AWS CDK

# Controls when the action will run.
on: 
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm install
        working-directory: backend-cdk

      - name: Install TS-Node
        run: 'sudo npm install -g ts-node'
        working-directory: backend-cdk

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'
        working-directory: backend-cdk

      - name: Synthesize CDK
        run: npx cdk synth
        working-directory: backend-cdk

      - name: CDK Deploy
        run: cdk deploy
        working-directory: backend-cdk